// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package discordmessage.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the DiscordMessage module

	/**
	* Automatically create the requested Webhook object, marked invalid, to be completed later. Every used Webhook should be defined and marked valid. But when an unknown webhook is used then it is added to be completed manually.
	*/
	public static boolean getAutoCreateWebhook()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("DiscordMessage.AutoCreateWebhook");
	}

	/**
	* The encryption key used to encrypt sensitive data like the Webhook URL which does not need authentication. Its length should exactly be 16 characters (128 bit).
	*/
	public static java.lang.String getEncryptionKey()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DiscordMessage.EncryptionKey");
	}

	/**
	* Please do not change this.
	*/
	public static java.lang.String getEncryptionPrefix()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DiscordMessage.EncryptionPrefix");
	}

	/**
	* Web service request timeout in seconds.
	*/
	public static java.lang.Long getRequestTimeout()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("DiscordMessage.RequestTimeout");
	}

	/**
	* When needed the module can be disabled on all runtime environments so it does not send messages. By default messages are sent in all environments other than development.
	*/
	public static boolean getSendEnabled()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("DiscordMessage.SendEnabled");
	}

	/**
	* By default messages are not sent in development environments. This prevents messages to be sent when running your app in Modeler/Studio Pro.
	*/
	public static boolean getSendEnabledInDev()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("DiscordMessage.SendEnabledInDev");
	}
}