// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package discordmessage.proxies;

public class ExecuteWebhookRequest
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject executeWebhookRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DiscordMessage.ExecuteWebhookRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		content("content"),
		username("username"),
		tts("tts");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ExecuteWebhookRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DiscordMessage.ExecuteWebhookRequest"));
	}

	protected ExecuteWebhookRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject executeWebhookRequestMendixObject)
	{
		if (executeWebhookRequestMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DiscordMessage.ExecuteWebhookRequest", executeWebhookRequestMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DiscordMessage.ExecuteWebhookRequest");

		this.executeWebhookRequestMendixObject = executeWebhookRequestMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ExecuteWebhookRequest.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static discordmessage.proxies.ExecuteWebhookRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return discordmessage.proxies.ExecuteWebhookRequest.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static discordmessage.proxies.ExecuteWebhookRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new discordmessage.proxies.ExecuteWebhookRequest(context, mendixObject);
	}

	public static discordmessage.proxies.ExecuteWebhookRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return discordmessage.proxies.ExecuteWebhookRequest.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of content
	 */
	public final java.lang.String getcontent()
	{
		return getcontent(getContext());
	}

	/**
	 * @param context
	 * @return value of content
	 */
	public final java.lang.String getcontent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.content.toString());
	}

	/**
	 * Set value of content
	 * @param content
	 */
	public final void setcontent(java.lang.String content)
	{
		setcontent(getContext(), content);
	}

	/**
	 * Set value of content
	 * @param context
	 * @param content
	 */
	public final void setcontent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.content.toString(), content);
	}

	/**
	 * @return value of username
	 */
	public final java.lang.String getusername()
	{
		return getusername(getContext());
	}

	/**
	 * @param context
	 * @return value of username
	 */
	public final java.lang.String getusername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.username.toString());
	}

	/**
	 * Set value of username
	 * @param username
	 */
	public final void setusername(java.lang.String username)
	{
		setusername(getContext(), username);
	}

	/**
	 * Set value of username
	 * @param context
	 * @param username
	 */
	public final void setusername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.username.toString(), username);
	}

	/**
	 * @return value of tts
	 */
	public final java.lang.Boolean gettts()
	{
		return gettts(getContext());
	}

	/**
	 * @param context
	 * @return value of tts
	 */
	public final java.lang.Boolean gettts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.tts.toString());
	}

	/**
	 * Set value of tts
	 * @param tts
	 */
	public final void settts(java.lang.Boolean tts)
	{
		settts(getContext(), tts);
	}

	/**
	 * Set value of tts
	 * @param context
	 * @param tts
	 */
	public final void settts(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean tts)
	{
		getMendixObject().setValue(context, MemberNames.tts.toString(), tts);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return executeWebhookRequestMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final discordmessage.proxies.ExecuteWebhookRequest that = (discordmessage.proxies.ExecuteWebhookRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DiscordMessage.ExecuteWebhookRequest";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
