// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package discordmessage.proxies;

public class Message
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DiscordMessage.Message";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MessageText("MessageText"),
		SendBy("SendBy"),
		DoTTS("DoTTS"),
		SendAsync("SendAsync");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Message(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DiscordMessage.Message"));
	}

	protected Message(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject)
	{
		if (messageMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DiscordMessage.Message", messageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DiscordMessage.Message");

		this.messageMendixObject = messageMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Message.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static discordmessage.proxies.Message initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return discordmessage.proxies.Message.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static discordmessage.proxies.Message initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new discordmessage.proxies.Message(context, mendixObject);
	}

	public static discordmessage.proxies.Message load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return discordmessage.proxies.Message.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MessageText
	 */
	public final java.lang.String getMessageText()
	{
		return getMessageText(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageText
	 */
	public final java.lang.String getMessageText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MessageText.toString());
	}

	/**
	 * Set value of MessageText
	 * @param messagetext
	 */
	public final void setMessageText(java.lang.String messagetext)
	{
		setMessageText(getContext(), messagetext);
	}

	/**
	 * Set value of MessageText
	 * @param context
	 * @param messagetext
	 */
	public final void setMessageText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String messagetext)
	{
		getMendixObject().setValue(context, MemberNames.MessageText.toString(), messagetext);
	}

	/**
	 * @return value of SendBy
	 */
	public final java.lang.String getSendBy()
	{
		return getSendBy(getContext());
	}

	/**
	 * @param context
	 * @return value of SendBy
	 */
	public final java.lang.String getSendBy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SendBy.toString());
	}

	/**
	 * Set value of SendBy
	 * @param sendby
	 */
	public final void setSendBy(java.lang.String sendby)
	{
		setSendBy(getContext(), sendby);
	}

	/**
	 * Set value of SendBy
	 * @param context
	 * @param sendby
	 */
	public final void setSendBy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sendby)
	{
		getMendixObject().setValue(context, MemberNames.SendBy.toString(), sendby);
	}

	/**
	 * @return value of DoTTS
	 */
	public final java.lang.Boolean getDoTTS()
	{
		return getDoTTS(getContext());
	}

	/**
	 * @param context
	 * @return value of DoTTS
	 */
	public final java.lang.Boolean getDoTTS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DoTTS.toString());
	}

	/**
	 * Set value of DoTTS
	 * @param dotts
	 */
	public final void setDoTTS(java.lang.Boolean dotts)
	{
		setDoTTS(getContext(), dotts);
	}

	/**
	 * Set value of DoTTS
	 * @param context
	 * @param dotts
	 */
	public final void setDoTTS(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean dotts)
	{
		getMendixObject().setValue(context, MemberNames.DoTTS.toString(), dotts);
	}

	/**
	 * @return value of SendAsync
	 */
	public final java.lang.Boolean getSendAsync()
	{
		return getSendAsync(getContext());
	}

	/**
	 * @param context
	 * @return value of SendAsync
	 */
	public final java.lang.Boolean getSendAsync(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SendAsync.toString());
	}

	/**
	 * Set value of SendAsync
	 * @param sendasync
	 */
	public final void setSendAsync(java.lang.Boolean sendasync)
	{
		setSendAsync(getContext(), sendasync);
	}

	/**
	 * Set value of SendAsync
	 * @param context
	 * @param sendasync
	 */
	public final void setSendAsync(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean sendasync)
	{
		getMendixObject().setValue(context, MemberNames.SendAsync.toString(), sendasync);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return messageMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final discordmessage.proxies.Message that = (discordmessage.proxies.Message) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DiscordMessage.Message";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
